### ISSUE TITLE
failed loading cafile stream

### ISSUE THREAD

**Issue by CoachForEyes** [Gypsyan/APNS_Safari_Push#1]
Hello,
I'm having a problem with the php script on my server : 

`E_WARNING Error in file notificationsSafari.php at line 113: failed loading cafile stream: `Entrust.net Certification Authority (2048).pem.pem'
  E_WARNING Error in file notificationsSafari.php at line 113: stream_socket_client(): Failed to enable crypto
  E_WARNING Error in file notificationsSafari.php at line 113: stream_socket_client(): unable to connect to ssl://gateway.push.apple.com:2195 (Unknown error)`

Line 113 is : 
`$fp = stream_socket_client(
                $this->push_apple, $err,
                $errstr, 60, STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT, $ctx );`

Seeing that on my server I don't find a php.ini satisfying conf (with a openssl.cafile field well provided) I commented the line:
`$stream_success = stream_context_set_option( $ctx, 'ssl', 'cafile', 'Entrust.net Certification Authority (2048).pem.pem' );`
And the script goes to the end, but I don't receive the notification. I verified the token, it's good. 
How to know where does it block ?

**Comment by AnanthaKrish** [comment]
@CoachForEyes I will get back to you. Looks like I have to update the code..

**Comment by AnanthaKrish** [comment]
@CoachForEyes Please follow this

https://github.com/Gypsyan/APNS_Safari_Push#where-to-get-the-entrust-root-ca-pem-file

```
1. Launch Keychain Assistant
2. click on System Root Certificate
3. Select the Certificates on the bottom-left
4. Right-click on Entrust.net Certification Authority (2048) and export with Entrust.net Certification Authority (2048).pem file name and choose as document format Privacy Enhanced Mail (.pem).

5. Now you can use this PEM file as Entrust Root Certification Authority in php to verify Apple Peer!
```

**Comment by CoachForEyes** [comment]
Thank you ! It's precisely what was missing.
